name: Unit Tests

on:
  push:

jobs:
  build:
    name: Build executable
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: apt-get update && apt-get install -y \
        build-essential \
        nasm

    - name: Build Pestilence
      run: make Pestilence