name: Unit Tests

on:
  push:

jobs:
  build:
    name: Build executable
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ilammy/setup-nasm@v1

    - name: Build Pestilence
      run: make Pestilence

    - name: Upload Pestilence
      uses: actions/upload-artifact@v4
      with:
        name: Pestilence
        path: ./Pestilence

  empty_test:
    name: Test without test folders or with empty test folders
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: Pestilence
    
    - name: Test without test folders
      run: ./Pestilence

    - name: Test with empty test folders
      run: mkdir -p /tmp/test && mkdir -p /tmp/test2
      run: ./Pestilence