name: Unit Tests

on:
  push:

jobs:
  build:
    name: Build executable
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ilammy/setup-nasm@v1

    - name: Build Pestilence
      run: make Pestilence

    - name: Upload Pestilence
      uses: actions/upload-artifact@v4
      with:
        name: Pestilence
        path: ./Pestilence

  no_folder_test:
    name: Test without test folders
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: Pestilence
        path: .

    - name: Make pestilence executable
      run: chmod +x ./Pestilence
    
    - name: Test without test folders
      run: ./Pestilence

  empty_folder_test:
    name: Test with empty test folders
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: Pestilence
        path: .

    - name: Make pestilence executable
      run: chmod +x ./Pestilence

    - name: Test with empty test folders
      run: mkdir -p /tmp/test && mkdir -p /tmp/test2 && ./Pestilence

  basic_echo_test:
    name: Basic infection of echo
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: Pestilence

    - name: Make pestilence executable
      run: chmod +x ./Pestilence

    - name: Prepare test
      run: mkdir -p /tmp/test && cp /bin/echo /tmp/test/echo

    - name: Infect echo
      run: ./Pestilence

    - name: Test echo has signature
      run: strings /tmp/test/echo | grep "Pestilence"

    - name: Run infected echo
      run: /tmp/test/echo "Hello, world!" > echo_output 

    - name: Check infected echo output
      run: echo "Hello, world!" > echo_expected && diff echo_output echo_expected
